### ISSUE TITLE
Null Exception when Enum value is null

### ISSUE THREAD

**Issue by filipe-silva** [StevenThuriot/dotnet-openapi-generator#5] opened 2023-10-29 19:48 UTC
Hi,

when I tried to generate an api from:
https://api-docs.firefly-iii.org/?urls.primaryName=2.0.10%20(v2)

It gave an exception for "AutoBudgetPeriod", although there are a few more enums, on this code:
`
class: SwaggerSchemaEnum
line 30: name = value.ToString() ?? "";
`

I fixed it by doing this:

`
else
{
    name = value?.ToString() ?? "";
}

if (string.IsNullOrWhiteSpace(name) == false)
{
    if (Char.IsDigit(name[0]))
    {
        name = "_" + name;
    }

    if (!unique.Add(name))
    {
        continue;
    }
}
`

but it doesn't seem right to me..

**Comment by LieselThuriot** [comment] 2023-10-29 23:43
Do you happen to have the json file you used to generate?
From what I can see, the link you posted only has yaml files available.

I will try to reproduce the issue and see what's going wrong if you can link me the file.

**Comment by LieselThuriot** [comment] 2023-10-30 00:15
I couldn't find the enum in the V2 you linked, but after looking at the yaml file for v1 I noticed this:

```yml
    AutoBudgetPeriod:
      type: string
      format: string
      example: "monthly"
      nullable: true
      description: "Period for the auto budget"
      enum:
        - daily
        - weekly
        - monthly
        - quarterly
        - "half-year"
        - yearly
        - null
```

Also pulled it through a YAML to JSON converter and got this:

```json
      "AutoBudgetPeriod": {
        "type": "string",
        "format": "string",
        "example": "monthly",
        "nullable": true,
        "description": "Period for the auto budget",
        "enum": [
          "daily",
          "weekly",
          "monthly",
          "quarterly",
          "half-year",
          "yearly",
          null
        ]
      }
```

It seems like it's adding null as one of the values for the nullable enums, which I did not expect nor have for the swagger documents I generated myself.

The fix for that is fairly easy and I will try and push it in the following days.

However, `"half-year"` is a whole other issue as there's no support yet for this. 
The code currently assumes the enum's can be directly ToString'ed for query parameters and System.Text.json has no support yet for `EnumMemberAttribute` when used in a body. 

This would require generating custom serializers when an enum has this and seeing it's only loosely coupled to System.Text.Json, that might be quite an annnoying hurdle to tackle 😢 Most likely I won't have a quick fix for this, but I will look into it.

**Comment by LieselThuriot** [comment] 2023-10-30 00:21
Referencing https://github.com/dotnet/runtime/issues/74385

**Comment by filipe-silva** [comment] 2023-10-30 08:57
> Do you happen to have the json file you used to generate? From what I can see, the link you posted only has yaml files available.
> 
> I will try to reproduce the issue and see what's going wrong if you can link me the file.

Hello! Sorry for the late reply it was night time already here.

Yes that's exactly the enum that gives an error, I converted to json and got the same result as you.
Sorry I thought it was on v2, I manually joined v1 and v2 and didn't notice it, well done catching that.

Great news for the null fix then!

As for the dash, I'd something like these anwsers:
Check if is has special chars:
-  char.IsLetterOrDigit
https://stackoverflow.com/questions/4503542/check-for-special-characters-in-a-string

Place an attribute description with the enum value as is:
- https://stackoverflow.com/questions/8852253/how-can-i-get-enum-to-contain-a-dash

And before creating the member, I'd take out the special chars:
- https://stackoverflow.com/questions/1120198/most-efficient-way-to-remove-special-characters-from-string

**Comment by LieselThuriot** [comment] 2023-10-31 15:52
So far, I've fixed most of the generating problems that came out of this swagger document on the linked dev branch.

The problem is that these solutions all require a **_custom serializer_** to be added to the serializer options. 

The difficulty there is that this generator is only very loosely coupled to `System.Text.Json` by default and tries not to make any assumptions which json serialization you're actually using. Or if you're even using Json as a serializer at all. These are all very easily overwritten in the `__ClientOptions` class. So far, this has always been very easy to do by adding the needed attributes as startup options with `System.Text.Json` defaults when omitted.

However, in this case, this would require also generating the Serializer itself, which is vastly different between `System.Text.Json`, `Newtonsoft` or let alone any other serialization solutions. Something the dev's should then do themselves and hopefully they don't forget or the API calls will fail

In essence, it would be very easy to generate something like this:

```csharp
public enum AutoBudgetPeriod
{
	daily,
	weekly,
	monthly,
	quarterly,
	[System.Runtime.Serialization.EnumMember(Value = "half-year")]half_year,
	yearly
}
```

This will work out of the box for `Newtonsoft`, but not for `System.Text.Json`. 
On top of the serializer, I also need to add support when these are used as query parameters.

I'm kind of hesitant to quickly add this functionality without thinking it through first. When dotnet8 releases next month, my main goal for this generator is to start preparing it to fully support `Native AOT` --> This will instantly break this solution.

Instead, I'm currently thinking I might add an option instead as a sort of "quick-fix" when working with API's like this:

`--enum-strings       Generate enums as string constants. Use this if the calling API contains enumerations that do not have valid names in C#`

Resulting in:

```csharp
public static class AutoBudgetPeriod
{
	public const string daily = "daily";
	public const string weekly = "weekly";
	public const string monthly = "monthly";
	public const string quarterly = "quarterly";
	public const string half_year = "half-year";
	public const string yearly = "yearly";
}
```


@glenndierckx  : Do you have an opinion on this?

**Comment by glenndierckx** [comment] 2023-11-10 14:59
Sorry for the late reply. I would try to avoid generating enum members as those constant values. Preferably it's indeed with an attribute like that EnumMember one. It indeed then needs a custom serializer, but that's just the cleanest way I think. Which reminds me, should we also add JsonPropertyNameAttributes for properties that don't match by default?

**Comment by LieselThuriot** [comment] 2023-11-10 15:01
Yes! I believe I already started implementing support for this on the branch. 
One of the contracts in the supplied swagger document for this issue contained a property called `0` which is also not a valid dotnet naming.

**Closed as completed** 2024-02-29 20:24 UTC
Labels: bug, enhancement
